%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "KannalaBrandt8"

# Left Camera calibration and distortion parameters (OpenCV)
Camera.fx: 286.221588134766
Camera.fy: 287.480102539062
Camera.cx: 419.467010498047 
Camera.cy: 386.97509765625

# Kannala-Brandt distortion parameters
Camera.k1: -0.0043481751345098
Camera.k2: 0.037125650793314
Camera.k3: -0.0355393998324871
Camera.k4: 0.00577297387644649

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 285.229187011719
Camera2.fy: 286.333709716797
Camera2.cx: 422.039001464844
Camera2.cy: 397.015991210938

# Kannala-Brandt distortion parameters
Camera2.k1: -0.00527892587706447
Camera2.k2: 0.0386337004601955
Camera2.k3: -0.0366357117891312
Camera2.k4: 0.00610797293484211

# Transformation matrix from right camera to left camera
#Tlr: !!opencv-matrix
#   rows: 3
#   cols: 4
#   dt: f
#   data: [ 1.0000,    0.0008,    0.0007,    0.1011,
#             -0.0008,    0.9989,    0.0469,    0.0019,
#             -0.0007,   -0.0469,    0.9989,    0.0010]

Tlr: !!opencv-matrix
  rows: 3
  cols: 4
  dt: f
  data: [ 0.999972, 0.00400718, -0.00635099, 0.0643047839403152,
          -0.00403926, 0.999979, -0.00504551, 0.000145973026519641,
          0.00633063, 0.00507102, 0.999967, -9.55924042500556e-05 ]

# Camera resolution
Camera.width: 848
Camera.height: 800

# Lapping area between images
Camera.lappingBegin: 0
Camera.lappingEnd: 847

Camera2.lappingBegin: 0
Camera2.lappingEnd: 847

# Camera frames per second
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40.0

Camera.bf: 19.3079

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8


# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 1
Viewer.PointSize:2
Viewer.CameraSize: 0.05
Viewer.CameraLineWidth: 2
Viewer.ViewpointX: 0
Viewer.ViewpointY: -10
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000
Viewer.ViewpointF: 2000